# Generated by Django 5.1.1 on 2024-11-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lost_items/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('prefecture', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
